function h = make_u_init(dim)
    switch dim
        case 2; h = @(x,y)   cos(2*pi*x).*sin(8*pi*y) + ...
                              2*sin(6*pi*y) + ...
                              3*sin(10*pi*x).*(cos(12*pi*y).^2);
        case 3; h = @(x,y,z) cos(2*pi*x).*sin(8*pi*y) + ...
                              2*sin(6*pi*y) + ...
                              3*sin(10*pi*x).*(cos(12*pi*y).^2) + ...
                              cos(2*pi*z);
    end
end